project/config/routes.rb
Rails.application.routes.draw do
  root 'contents#index'

  resources :contents, only: [:show, :index]

end

project/app/models/content.rb
class Content < ActiveRecord::Base

  validates :title, presence: true
  validates :title, length: { is: 6 }
  validates :title, uniqueness: true

end

project/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

project/app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :find_content, only: [:update, :edit, :show]

  def index
    @hola = "Hola muchachos"
    @contenidos = Content.all
  end

  # Patch del /:id
  def update
    if @content.update_attributes(permited_params)
      redirect_to contents_path
    else
      render :new
    end
  end

  # GET de /:id/edit
  def edit
    render :new
  end

  # DELETE /:id
  def destroy
  end

  # GET /:id
  def show
  end

  # GET /new
  def new
    @content = Content.new
  end

  # POST /
  def create
    @content = Content.new(permited_params)
    if @content.save
      redirect_to contents_path
    else
      render :new
    end
  end

  def find_content
    @content = Content.find(params[:id])
  end

  def permited_params
    params.required(:content).permit(:title, :description, :order)
  end
end

project/app/helpers/application_helper.rb
module ApplicationHelper
end

project/app/helpers/contents_helper.rb
module ContentsHelper
end

project/app/views/contents/blah.html.erb
<h1>Contents#blah</h1>
<p>Find me in app/views/contents/blah.html.erb</p>

project/app/views/contents/index.html.erb
<h1>Contents#index</h1>
<p>Find me in app/views/contents/index.html.erb</p>

<p>
  <%= @hola %>
</p>

<%= link_to 'Crear nuevo contenido', new_content_path %>
<%= link_to 'Todos los contenidos', contents_path %>

<% for contenido in @contenidos %>
  <h1><%= link_to contenido.title, content_path(contenido) %></h1>
<% end %>

<!-- 
  link_to("texto", url, {class, method, html})
 -->

project/app/views/contents/new.html.erb
<h1>esto es el formulario</h1>
<% for error in @content.errors.full_messages %>
  <%= error.messages %>
<% end %>
<%= form_for @content do |f| %>
<p>
  <%= f.label :title %>
  <%= f.text_field :title %>
</p>
<p>
  <%= f.label :description %>
  <%= f.text_area :description %>
</p>
<p><%= f.label :order %>
<%= f.number_field :order %></p>

<p>
  <%= f.submit %>
</p>
<% end %>

project/app/views/contents/show.html.erb
<%= link_to 'Todos los contenidos', contents_path %>
<%= link_to 'Editar', edit_content_path(@content) %>

<h1>
  <%= @content.title %>
</h1>

<p>
  <%= @content.description %>
</p>

project/app/views/contents/update.html.erb
<h1>Contents#update</h1>
<p>Find me in app/views/contents/update.html.erb</p>

project/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>